questions = [
    "Is the keyword related to nature or a natural phenomenon ?",
    "Is the keyword alive?",
    "Is it something you can find in a bathroom?",
    "Does the keyword have any moving parts?",
    "Is the keyword something you can eat?",
    "Is the keyword a piece of technology?",
    "Can the keyword be found indoors?",
    "Does the keyword have a specific color?",
    "Is the keyword something that moves?",
    "Is the keyword used for entertainment?",
    "Is the keyword larger than a breadbox?",
    "Is the keyword a threat for humans?",
    "Is the keyword used in a specific season or time of year?",
    "Is the keyword something you wear?",
    "Does the keyword have any relation to water?",
    "Can the keyword be found in a typical household?",
    "Is the keyword commonly used by children?",
    "Is the keyword related to a particular profession or job?",
    "Can the keyword be bought in a store?",
    "Does the keyword have an engine or motor?",
    "Is the keyword considered a luxury item?",
]
guesses = [
    "tomato",
    "internet",
    "sunscreen",
    "spaceship",
    "car seat",
    "bacon",
    "parallel bars",
    "movie poster",
    "sippy cup",
    "pot holder",
    "guitar",
    "lion",
    "soccer ball",
    "refrigerator",
    "unicorn",
    "diamond ring",
    "chessboard",
    "lint roller",
    "edible flowers",
    "pearl",
    "wingsuit",
]

first_questions = [
    {
        "question": "Is the keyword man-made?",
        "yes": "man-made",
        "no": "not man-made",
    },
    {
        "question": "Is the keyword something that can be held in your hand?",
        "yes": "hand holdable",
        "no": "not hand holdable",
    },
]
